//CHARACTERS OBJECT
//Object containing all of the characters along with their stats
let theCharacters = [
	{
		name: "landmine",
		faction: "autobot",
		health: 10,
		currentHealth: 10,
		ultimate: 10,
		currentUltimate: 0,
		firepower: 5,
		speed: 3,
		range: 5,
	},
	{
		name: "ransack",
		faction: "ransack",
		health: 5,
		currentHealth: 5,
		ultimate: 10,
		currentUltimate: 0,
		firepower: 3,
		speed: 5,
		range: 5,
	},
	{
		name: "dunerunner",
		faction: "autobot",
		health: 5,
		currentHealth: 5,
		ultimate: 10,
		currentUltimate: 0,
		firepower: 3,
		speed: 5,
		range: 7,
	},
	{
		name: "prowl",
		faction: "ransack",
		health: 10,
		currentHealth: 10,
		ultimate: 10,
		currentUltimate: 0,
		firepower: 2,
		speed: 3,
		range: 6,
	},
	{
		name: "brainstorm",
		faction: "autobot",
		health: 10,
		currentHealth: 10,
		ultimate: 10,
		currentUltimate: 0,
		firepower: 2,
		speed: 6,
		range: 8,
	},
	{
		name: "overcast",
		faction: "ransack",
		health: 10,
		currentHealth: 10,
		ultimate: 10,
		currentUltimate: 0,
		firepower: 2,
		speed: 6,
		range: 8,
	},
	{
		name: "ironhide",
		faction: "autobot",
		health: 20,
		currentHealth: 20,
		ultimate: 10,
		currentUltimate: 0,
		firepower: 3,
		speed: 3,
		range: 4,
	},
	{
		name: "onslaught",
		faction: "ransack",
		health: 30,
		currentHealth: 30,
		ultimate: 10,
		currentUltimate: 0,
		firepower: 4,
		speed: 2,
		range: 4,
	},
	{
		name: "overhaul",
		faction: "autobot",
		health: 10,
		currentHealth: 10,
		ultimate: 10,
		currentUltimate: 0,
		firepower: 3,
		speed: 5,
		range: 0,
	},
	{
		name: "crumplezone",
		faction: "ransack",
		health: 20,
		currentHealth: 20,
		ultimate: 10,
		currentUltimate: 0,
		firepower: 2,
		speed: 5,
		range: 5,
	},
]